//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuisBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuisBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;airports&gt;&lt;airport&gt;&lt;name&gt;Huntsville International&lt;/name&gt;&lt;shortcode&gt;HSV&lt;/shortcode&gt;&lt;city&gt;Huntsville&lt;/city&gt;&lt;state&gt;AL&lt;/state&gt;&lt;latitude&gt;34.6486&lt;/latitude&gt;&lt;longitude&gt;-86.7751&lt;/longitude&gt;&lt;utc&gt;-6&lt;/utc&gt;&lt;dst&gt;True&lt;/dst&gt;&lt;precheck&gt;true&lt;/precheck&gt;&lt;checkpoints&gt;&lt;checkpoint&gt;&lt;id&gt;1&lt;/id&gt;&lt;longname&gt;HSV-A&lt;/longname&gt;&lt;shortname&gt;HSV-A&lt;/shortname&gt;&lt;/checkpoint&gt;&lt;/checkpoints&gt;&lt;/airport&gt;&lt;airport&gt;&lt;name&gt;Mobile Regional&lt;/name&gt;&lt;shortcode&gt;MOB&lt;/shortcode&gt;&lt;city&gt;Mobile&lt;/city&gt;&lt;state&gt;AL&lt;/state&gt;&lt;latitude&gt;30.68 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Airports {
            get {
                return ResourceManager.GetString("Airports", resourceCulture);
            }
        }
    }
}
